Repository bestivil/COMP4024-G13, pull requests merged in 2024-03, with the labels that each got.

#105 locked aspect ratio, made HD, locked alignment, and fixed layering
  Assembly-CSharp.csproj
  Assets/Code/CollisionScoring.cs
  Assets/Scenes/CosmicWordQuest.unity
  Assets/Scenes/StartScreen.unity
  GameLogic.csproj
  Library/Bee/bee_backend.info
  Library/EditorUserBuildSettings.asset
  Library/LastSceneManagerSetup.txt
  Library/PackageManager/ProjectCache
  Library/PackageManager/ProjectCache.md5
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
  TestsPlay.csproj
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2022.dwlt
Labels: bug

#106 fix: only one audio listener per scene
  Assets/Code/ExplosionSound.cs
  Assets/Scenes/CosmicWordQuest.unity
  Assets/Scenes/StartScreen.unity
  Library/ShaderCache/EditorEncounteredVariants
  ProjectSettings/TagManager.asset
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2022.dwlt
Labels: bug

#111 test: make sure all planets are visible
  Assets/Images.meta
  Assets/Images/image 19.png
  Assets/Images/image 19.png.meta
  Assets/Tests/TestsPlay/Planet1exists.cs
  Assets/Tests/TestsPlay/Planet1exists.cs.meta
  Assets/Tests/TestsPlay/Planet2exists.cs
  Assets/Tests/TestsPlay/Planet2exists.cs.meta
  Assets/Tests/TestsPlay/Planet3exi.cs
  Assets/Tests/TestsPlay/Planet3exi.cs.meta
  Assets/Tests/TestsPlay/Planet4exists.cs
  Assets/Tests/TestsPlay/Planet4exists.cs.meta
  Assets/Tests/TestsPlay/Planet5exists.cs
  Assets/Tests/TestsPlay/Planet5exists.cs.meta
Labels: test

#112 test: spaceship is visible
  Assets/Tests/TestsPlay/SpaceshipExists.cs
  Assets/Tests/TestsPlay/SpaceshipExists.cs.meta
Labels: test

#115 test: made sure back and leaderboard buttons are visible
  Assets/Tests/TestsPlay/BackButtonExists.cs
  Assets/Tests/TestsPlay/BackButtonExists.cs.meta
  Assets/Tests/TestsPlay/LeaderboardButtonExists.cs
  Assets/Tests/TestsPlay/LeaderboardButtonExists.cs.meta
  Library/PackageManager/ProjectCache
  Library/PackageManager/ProjectCache.md5
  UserSettings/Layouts/default-2022.dwlt
Labels: test

#119 test: start menu buttons all show up
  Assets/Scenes/StartScreen.unity
  Assets/Tests/TestsPlay/QuitButtonExists.cs
  Assets/Tests/TestsPlay/QuitButtonExists.cs.meta
  Assets/Tests/TestsPlay/StartButtonExists.cs
  Assets/Tests/TestsPlay/StartButtonExists.cs.meta
  Assets/Tests/TestsPlay/TutorialButtonExists.cs
  Assets/Tests/TestsPlay/TutorialButtonExists.cs.meta
  Library/Bee/bee_backend.info
  Library/EditorUserBuildSettings.asset
  Library/LastSceneManagerSetup.txt
  Library/PackageManager/ProjectCache
  Library/PackageManager/ProjectCache.md5
  ProjectSettings/TagManager.asset
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2022.dwlt
Labels: test

#120 feature: planets explode on collission
  Assembly-CSharp.csproj
  Assets/Code/Explosion.cs
  Assets/Code/Explosion.cs.meta
  Assets/Scenes/CosmicWordQuest.unity
  Assets/ToonExplosion v1.0.meta
  Assets/ToonExplosion v1.0/Animations.meta
  Assets/ToonExplosion v1.0/Animations/ExpAnimator.controller
  Assets/ToonExplosion v1.0/Animations/ExpAnimator.controller.meta
  Assets/ToonExplosion v1.0/Animations/Explosion.anim
  Assets/ToonExplosion v1.0/Animations/Explosion.anim.meta
  Assets/ToonExplosion v1.0/Prefabs.meta
  Assets/ToonExplosion v1.0/Prefabs/Explosion.prefab
  Assets/ToonExplosion v1.0/Prefabs/Explosion.prefab.meta
  Assets/ToonExplosion v1.0/Textures.meta
  Assets/ToonExplosion v1.0/Textures/Explosion.png
  Assets/ToonExplosion v1.0/Textures/Explosion.png.meta
  GameLogic.csproj
  Library/PackageManager/ProjectCache.md5
  ProjectSettings/BurstAotSettings_StandaloneWindows.json
  TestsPlay.csproj
  UserSettings/Layouts/default-2022.dwlt
Labels: feature

#127 refactor/comment on all code modules
  Assembly-CSharp.csproj
  Assets/Code/BulletUpDown.cs
  Assets/Code/CameraAdjustment.cs
  Assets/Code/CameraAdjustment.cs.meta
  Assets/Code/CollisionScoring.cs
  Assets/Code/DatabaseAccess.cs
  Assets/Code/EnterName.cs
  Assets/Code/Explosion.cs
  Assets/Code/ExplosionSound.cs
  Assets/Code/GameManager.cs
  Assets/Code/JsonTest.cs
  Assets/Code/Leaderboard.json
  Assets/Code/Leaderboard.json.meta
  Assets/Code/NameScene.cs
  Assets/Code/OutBounds.cs
  Assets/Code/PlanetLangSetup.cs
  Assets/Code/PlanetLangSetup.cs.meta
  Assets/Code/PlayerData.cs
  Assets/Code/SpaceshipLeftRight.cs
  Assets/Code/SpaceshipOutsideView.cs
  Assets/Code/StateController.cs
  Assets/Code/TimerLv1.cs
  Assets/Code/accessJSON.cs
  GameLogic.csproj
  Library/Bee/bee_backend.info
  Library/LastSceneManagerSetup.txt
  Library/PackageManager/ProjectCache
  Library/PackageManager/ProjectCache.md5
  TestsPlay.csproj
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2022.dwlt
Labels: refactor

#129 fix script and change to load correct scene
  Assets/Code/LoadMenu.cs
Labels: bug, refactor

#130 fix: leaderboard scene refreshes after 5 seconds
  Assets/Code/LeaderboardManager.cs
  Assets/Code/StartGame.cs
  Assets/Database/ScoresCSV.csv
Labels: bug

#132 fix: timer, level, score showing correctly
  Assets/Code/GameManager.cs
  Assets/Code/Timer.cs
  Assets/Code/Timer.cs.meta
  Assets/Scenes/CosmicWordQuest.unity
  Assets/Scenes/StartScreen.unity
  GameLogic.csproj
  Library/EditorUserBuildSettings.asset
  ProjectSettings/EditorBuildSettings.asset
Labels: bug

#134 fix: quit button on StartScreen works in the build
  Assets/Code/Quit.cs
  Assets/Code/Quit.cs.meta
  Assets/Scenes/StartScreen.unity
  GameLogic.csproj
  Library/LastSceneManagerSetup.txt
  ProjectSettings/ProjectSettings.asset
  UserSettings/EditorUserSettings.asset
Labels: bug

#135 docs: added instructions to run in unity
  README.md
Labels: documentation

#139 code refactoring and test editing
  .DS_Store
  Assembly-CSharp.csproj
  Assets/Code/StateController.cs
  Assets/Scenes/CosmicWordQuest.unity
  Assets/Scenes/HighScoreScreen.unity
  Assets/Tests/TestsPlay/BackButtonExists.cs
  Assets/Tests/TestsPlay/Bullet-x-cord.cs
  Assets/Tests/TestsPlay/BulletExist.cs
  Assets/Tests/TestsPlay/LeaderboardButtonExists.cs
  Assets/Tests/TestsPlay/Planet1exists.cs
  Assets/Tests/TestsPlay/Planet2exists.cs
  Assets/Tests/TestsPlay/Planet3Exists.cs
  Assets/Tests/TestsPlay/Planet3Exists.cs.meta
  Assets/Tests/TestsPlay/Planet4exists.cs
  Assets/Tests/TestsPlay/Planet5exists.cs
  Assets/Tests/TestsPlay/SpaceExist.cs
  Assets/Tests/TestsPlay/SpaceshipExists.cs
  Assets/Tests/TestsPlay/SpaceshipTests.cs
  Assets/Tests/TestsPlay/StartMenuTests/QuitButtonExists.cs
  Assets/Tests/TestsPlay/StartMenuTests/StartButtonExists.cs
  Assets/Tests/TestsPlay/StartMenuTests/TutorialButtonExists.cs
  Assets/Tests/TestsPlay/spaceshipOutbound.cs
  GameLogic.csproj
  Library/Bee/bee_backend.info
  Library/EditorUserBuildSettings.asset
  Library/LastSceneManagerSetup.txt
  Library/PackageManager/ProjectCache
  Library/PackageManager/ProjectCache.md5
  ProjectSettings/ProjectSettings.asset
  TestsPlay.csproj
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2022.dwlt
Labels: bug, test, refactor

#141 Week 5 documentation and notes
  .DS_Store
  Documentation/Meeting Notes/.DS_Store
  Documentation/Meeting Notes/Week 5.md
  Documentation/Week 4/BurndownChartWeek4.png
  Documentation/Week 4/BurndownChartWeek4CloseUp.jpeg
  Documentation/Week 5/BurndownChartWeek5.png
  Documentation/Week 5/BurndownChartWeek5Detailed.png
  Documentation/Week 5/CompletedTests.jpeg
Labels: documentation

#143 fix: attempted fix for leaderboard screen to work outside of demo ver…
  .DS_Store
  Assets/Code/GameManager.cs
  Assets/Code/LeaderboardManager.cs
  Assets/ScoresCSV.csv
  Assets/ScoresCSV.csv.meta
  Library/EditorUserBuildSettings.asset
  Library/LastSceneManagerSetup.txt
  TestsPlay.csproj
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2022.dwlt
Labels: bug

#144 finished burndown charts
  Documentation/.DS_Store
  Documentation/BurndownChartWeek5.png
  Documentation/BurndownChartWeek5Detailed.png
  Documentation/Week 5/.DS_Store
  Documentation/Week 5/BurndownChartWeek5.png
  Documentation/Week 5/BurndownChartWeek5Detailed.png
Labels: documentation
