Repository bestivil/COMP4024-G13, pull requests merged in 2024-02, with the labels that each got.

#16 file: added flow chart (UML), MVP, User Req docs
  Week 2/FLow chart.png
  Week 2/Minimum Viable Product (MVP) outline for the language learning game_.pdf
  Week 2/User Requirements.pdf
Labels: documentation

#18 4 documentation for team git guide git branching git commits acceptance criteria
  Documentation/Git Branching Guide.md
  Documentation/Git Commit Guide.md
  Documentation/GitGuide.md
Labels: documentation

#35 file: added meeting notes with sprint retro
  Meeting Notes/Week 3a.md
Labels: documentation

#42 test:bullet stays on x cord
  Assets/Tests/TestsPlay/Bullet-x-cord.cs
Labels: paired, test

#61 feat: added timer function to game
  Assets/Code/TimerLv1.cs
  Assets/Code/TimerLv1.cs.meta
Labels: feature

#62 feat: user can input name in dialog box after game
  Assembly-CSharp.csproj
  Assets/Code/OutBounds.cs
  Assets/Code/TimerLv1.cs
  Assets/Scenes/CosmicWordQuest.unity
  GameLogic.csproj
  Library/APIUpdater/project-dependencies.graph
  Library/Bee/bee_backend.info
  Library/EditorUserBuildSettings.asset
  Library/PackageManager/ProjectCache
  Library/PackageManager/ProjectCache.md5
  ProjectSettings/BurstAotSettings_StandaloneOSX.json
  ProjectSettings/CommonBurstAotSettings.json
  ProjectSettings/TagManager.asset
  TestsPlay.csproj
  UserSettings/Layouts/default-2022.dwlt
Labels: feature

#77 feat: the game is split into 2 levels
  Assembly-CSharp.csproj
  Assets/Code/GameManager.cs
  Assets/Code/GameManager.cs.meta
  Assets/Code/TimerLv1.cs
  Assets/Scenes/CosmicWordQuest.unity
  Assets/Visuals/back_button.png
  Assets/Visuals/back_button.png.meta
  Assets/Visuals/leaderboard.png
  Assets/Visuals/leaderboard.png.meta
  GameLogic.csproj
  Library/APIUpdater/project-dependencies.graph
  Library/Bee/bee_backend.info
  Library/PackageManager/ProjectCache
  Library/PackageManager/ProjectCache.md5
  ProjectSettings/TagManager.asset
  TestsPlay.csproj
  UserSettings/Layouts/default-2022.dwlt
Labels: feature

#78 fix: amended issues after rebasing previous commit
  Assets/Code/GameManager.cs
  Assets/Scenes/CosmicWordQuest.unity
  Library/APIUpdater/project-dependencies.graph
  Library/PackageManager/ProjectCache.md5
  UserSettings/Layouts/default-2022.dwlt
Labels: bug

#80 feat: name and score persisted across levels
  Assets/Code/EnterName.cs
  Assets/Code/EnterName.cs.meta
  Assets/Code/GameManager.cs
  Assets/Code/NameScene.cs
  Assets/Code/NameScene.cs.meta
  Assets/Scenes/CosmicWordQuest.unity
  Assets/Scenes/HighScoreScreen.unity
  Assets/Scenes/HighScoreScreen.unity.meta
  Assets/Scenes/Leaderboard.unity
  Assets/Visuals/high_scores.png
  Assets/Visuals/high_scores.png.meta
  GameLogic.csproj
  Library/APIUpdater/project-dependencies.graph
  Library/LastSceneManagerSetup.txt
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/TagManager.asset
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2022.dwlt
Labels: feature

#82 fix: score accumulates rather than reset
  Assets/Code/CollisionScoring.cs
  Assets/Code/GameManager.cs
Labels: bug

#89 file: burndown charts for week 4
  Documentation/Meeting Notes/BurndownChartWeek4.png
  Documentation/Meeting Notes/BurndownChartWeek4CloseUp.jpeg
Labels: documentation

#84 initial week4.md commit
  Assets/Tests/TestsPlay/spaceshipOutbound.cs
  Documentation/Meeting Notes/Week 4.md
  Documentation/Meeting Notes/image-7.png
  Library/LastSceneManagerSetup.txt
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2022.dwlt
Labels: documentation

#94 fix: test for spaceship out of bounds
  Assembly-CSharp.csproj
  Assets/Scenes/CosmicWordQuest.unity
  Assets/Tests/.DS_Store
  Assets/Tests/TestsPlay/spaceshipOutbound.cs
  GameLogic.csproj
  Library/Bee/bee_backend.info
  Library/EditorUserBuildSettings.asset
  Library/LastSceneManagerSetup.txt
  Library/PackageManager/ProjectCache
  Library/PackageManager/ProjectCache.md5
  TestsPlay.csproj
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2022.dwlt
Labels: bug
